# Generated by Django 3.0.8 on 2020-07-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
