# Generated by Django 3.0.8 on 2020-07-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rfidtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidtoken',
            old_name='image',
            new_name='token',
        ),
    ]
